//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace erp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public System.Guid idDepartment { get; set; }
        public string nameDepartment { get; set; }
        public Nullable<System.Guid> specialityCode { get; set; }
        public System.Guid departmentLeadId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Speciality Speciality { get; set; }
    }
}
