//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace erp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Departments = new HashSet<Department>();
            this.Groups = new HashSet<Group>();
            this.Subjects = new HashSet<Subject>();
        }
    
        public System.Guid codeEmployee { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string midName { get; set; }
        public Nullable<System.DateTime> dateofBirth { get; set; }
        public int positionCode { get; set; }
        public string addrr { get; set; }
        public Nullable<int> phoneNum { get; set; }
        public string email { get; set; }
        public System.DateTime dateBegin { get; set; }
        public Nullable<System.DateTime> dateEnd { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Department> Departments { get; set; }
        public virtual Position Position { get; set; }
        public virtual EmployeeLogin EmployeeLogin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Group> Groups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Subject> Subjects { get; set; }
    }
}
