//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace erp
{
    using System;
    using System.Collections.Generic;
    
    public partial class studyMark
    {
        public Nullable<int> idSubj { get; set; }
        public System.Guid recordId { get; set; }
        public Nullable<int> studentId { get; set; }
        public Nullable<int> markSubj { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
