//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace erp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.studyMarks = new HashSet<studyMark>();
        }
    
        public int codePerson { get; set; }
        public string firstName { get; set; }
        public string midName { get; set; }
        public string lastName { get; set; }
        public Nullable<System.DateTime> dateofBirth { get; set; }
        public int grupCode { get; set; }
        public string addrr { get; set; }
        public string phoneNum { get; set; }
        public string email { get; set; }
        public string parentPhoneNum { get; set; }
        public System.DateTime dateBegin { get; set; }
        public Nullable<System.DateTime> dateEnd { get; set; }
        public string reasonEnd { get; set; }
        public Nullable<bool> isContractor { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual StudentLogin StudentLogin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<studyMark> studyMarks { get; set; }
    }
}
